/**
 * SEO copy lives in data/seo-intent-map.json (generated by scripts/seo/build_intent_map.py from hand-written titles and
 * descriptions in scripts/seo/seo_copy.py). Pages call seoMeta(path) so every indexable page gets one reviewed, unique
 * title + meta description, while H1s stay owned by the content files.
 */
import type { Metadata } from "next";
import map from "../../../data/seo-intent-map.json";
import { pageMetadata } from "@/lib/seo/metadata";

export type IntentEntry = {
  kind: string;
  primaryQuery: string;
  secondaryQueries: string[];
  intent: string;
  funnel: string;
  title: string;
  metaDescription: string;
  h1: string;
};

const pages = (map as unknown as { pages: Record<string, IntentEntry> }).pages;

export function intentFor(path: string): IntentEntry | undefined {
  return pages[path];
}

export function seoMeta(
  path: string,
  extra: Partial<Pick<Parameters<typeof pageMetadata>[0], "type" | "modified" | "languages" | "noindex">> = {},
): Metadata {
  const e = pages[path];
  if (!e) throw new Error(`No SEO entry for ${path} in data/seo-intent-map.json — run scripts/seo/build_intent_map.py`);
  return pageMetadata({ title: e.title, absoluteTitle: true, description: e.metaDescription, path, ...extra });
}
